### ISSUE TITLE
Designing a new API

### ISSUE THREAD

**Issue by eemeli** [messageformat/messageformat#183]
I'm putting together a new system for defining and accessing messages from JavaScript. The basic idea is to have a language that's suitably JavaScript-ish that it fits in naturally in an ES6 context without losing the flexibility of ICU MessageFormat, while providing tools for maintaining the translations both when they change in the source, and when they get updated by the translators.

My current API draft looks like this:

```js
import msg, { plural, select } from './messages.yml'

msg.getAvailableLocales()  // ['en', ...]
msg.locale = 'en'  // optional, default 'en'

// 'This is Bob the Door'
const name = 'Bob the Door'
msg(name, 'This is {0}')
msg({ name }, 'This is {name}')
msg`This is ${name}`

// 'There are 4 doors'
const count = 4
plural(count, {
  one: 'There is one door',
  other: 'There are # doors'
})
msg`There {${plural(count, {
  one: 'is one door',
  other: 'are # doors'
})}}`
msg`There {${count}, plural,
  one{is one door}
  other{are # doors}
}`

// 'The door is red'
const isRed = true
select(isRed, { true: 'The door is red', other: `The door is blue` })
msg`The door is ${select(isRed, { true: 'red', other: 'blue' })}`
msg`The door is {${isRed}, select, true{red} other{blue}}`
```

Would this be something that might interest you and/or would you have recommendations for how to improve the above syntax? Are there problems with messageformat that you experience that this sort of syntax could help with? The main differences between this and the format natively used by messageformat is the use of full strings as keys, and the avoidance of calling the message functions directly.

The trick here would be that there'd be an associated [Babel](https://babeljs.io/) plugin that could take this JavaScript and update the associated `messages.yml` file while it's being transpiled. The format of that YAML file also needs to determined. Why YAML? Mainly because unlike JSON it supports comments and multi-line strings, which makes it more translator-friendly.

Other tools could then relatively easily extract untranslated strings from the YAML and output them in a form that'd be easier for e.g. translation agencies to deal with, as well as enabling re-import of their processed work.

The prime reason I'm posting this here is that messageformat is an essential part of the tools required to make something like this work, as it allows for the runtime compilation of the translation strings. For an example of what's already possible, have a look at [messageformat-loader](/messageformat/loader) and [messageformat-yaml-loader](/eemeli/messageformat-yaml-loader) (the latter still under my own namespace, as it's very much a work in progress).

**Comment by eemeli** [comment]
Noting here some relevant prior art:
- https://github.com/yahoo/babel-plugin-react-intl
- https://github.com/harmboschloo/babel-plugin-extract-tags
- https://github.com/rtymchyk/babel-plugin-extract-text
- https://github.com/format-message/format-message/tree/master/packages/babel-plugin-extract-format-message
- https://github.com/getsentry/babel-gettext-extractor

**Comment by SlexAxton** [comment]
I think this definitely has legs. I'd tend to think it would live as a separate project under the same namespace rather than being an option inside of messageformat.js.

I use `babel-plugin-react-intl` a bunch at work, and it's pretty nice flow, but sometimes a bummer when you have to build your whole app to extract strings.

My main concern is that without bindings into major libraries, it wouldn't be able to gain much steam as a 'standardish' API. And that once you brought something like this into something like React, you'd end up needing declarative components anyways, so you'd maybe lose some of your template string magic capabilities.

Anyways, totally down with you building a MessageFormat++ lib in the namespace, and happy to give slow feedback.

**Comment by eemeli** [comment]
Working with a real example, here's some code that I wish I could write -- an implementation of a component that I'm actually working on, and for which the code currently is nowhere near as clean:

```ts
import msg, { select } from 'messageformat-x'
import { list, time } from 'messageformat-x-y'

const itemLocation = (loc?: string[], start?: Date, end?: Date): string => {
  let locStr = ''
  if (loc) {
    const otherLoc = list(loc.slice(1)) || undefined
    locStr = msg`${loc[0]}${select(otherLoc, {
      undefined: '',
      other: ` (${otherLoc})`
    })}`
  }
  const timeStr = start && select(start, {
    undefined: '',
    other: time(start) + select(end, {
      undefined: '',
      other: ` - ${time(end)}`
    })
  })
  return list([locStr, timeStr])
}
```

For single-locale use, that should "just work" with no configuration at all, allowing for an easy start. In fact, there's no need to even run the message compiler as it's all JavaScript.

For multiple locales, the compiled code ends up completely different. The messages will need to get compiled into MessageFormat and written to some data/config file, the API will need to provide some way of switching between locales, and we need a babel plugin to replace the JS appropriately.

Using YAML as the target file format, it would end up with contents somewhat like the following. Interesting details to note are the variable name captures and the function nesting.
```yaml
# source: itemLocation, line 9
# variables: 0, otherLoc
#   0: loc[0]
# function: select
locStr: |- 
  {0}{otherLoc, select,
    undefined {}
    other { ({otherLoc})}
  }

# source: itemLocation, line 14
# variables: start, end
# functions: select, time
timeStr: |-
  {start, select,
    undefined {}
    other {start, time}{end, select,
      undefined {}
      other { - {end, time}}
    }
  }
```

To make that happen, we need to convert the input JavaScript AST into a MessageFormat AST, and then stringify that prettily while extracting contextual info for the comments.

The tricky bit is making all of this appear seamless to the user, and to make sure that updates to the parts of the source that we're using to connect the JS and YAML/MessageFormat data (variable names most significantly) can be automatically updated to all of the localization files.

**Comment by eemeli** [comment]
Closing this, as the implementation is progressing in [eemeli/messages](/eemeli/messages).
