### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by eemeli** [messageformat/messageformat#191]
Along with the upcoming 2.0 release, I've gone through and reworked how the website is built. Up to now, we've been using a Jekyll site built from a [separate repo](/messageformat/messageformat.github.io) for the main contents, and JSDoc for the API.

Maintaining two separate site generators has been a bit of a pain, and the website has lagged a bit in getting updated. This is not good.

So what I've done is [fork](/messageformat/docstrap) the [Docstrap theme](https://docstrap.github.io/docstrap/) for JSDoc, and fiddle with it enough that it can be used to host everything. As with the logo, I got some UI design help from Antti Tolppanen. I've also added the `docs/` folder to this repo, so that we can much more easily keep it updated.

The old site is still being served at https://messageformat.github.io/, and the v2 version is at https://messageformat.github.io/messageformat.js/. Unfortunately this does mean that the online API docs needed to be moved, because of a namespace conflict.

@SlexAxton, could you look through the new site, and see how you like it?

**Comment by SlexAxton** [comment]
Just read through it. Looks beautiful, seems to be pretty up to date. All for switching over whenever you want.
