### ISSUE TITLE
Problems with Typescript and the default export

### ISSUE THREAD

**Issue by mbarz** [messageformat/messageformat#199]
After #198 got resolved, I got some problems using the package with the included typedefinitions. `import * as MessageFormat from 'messageformat'` is not possible here.

> Module '"messageformat"' resolves to a non-module entity and cannot be imported using this construct.

To get the "export = ..." working I had to set "allowSyntheticDefaultImports": true in my tsconfig.json. Then I am able to use the package with `import MessageFormat from 'messageformat';`. Is there a better way to get this working?

As a first step it could maybe help to change `export = MessageFormat` to `export default MessageFormat` in the definition file.
Then I would be able to do `import { default as MessageFormat } from 'messageformat';`

As a next step I would be happy to be able to get the MessageFormat also nested in the module like `import { MessageFormat } from 'messageformat';`

**Comment by eemeli** [comment]
Apologies; I don't use TypeScript myself so don't really know what's needed to resolve this. Is this serious enough that we should revert the `index.d.ts` inclusion, and/or is there a simple fix that could be applied? Pull requests on this would be most welcome.

**Comment by eemeli** [comment]
Should be fixed now with #200.
