### ISSUE TITLE
Can not define a language with more than 2 characters in its code

### ISSUE THREAD

**Issue by mmanista** [messageformat/messageformat#205]
So, I am trying to make messageformat working with Angular 6 (Angular CLI) setup.
I have already done the entire research and found out that the source of a bug is the language key.

What happens is the following:
- if I provide the translation strings without the ICU format, everything works fine in all cases
- if I provide the translation strings that use ICU format and the language code has more than 2 characters (e.g. en_GB - the filename containing the translations would then be named en_GB.json - loading those with HTTP loader) - it breaks and throws errors:
```
ERROR TypeError: Cannot read property 'toString' of undefined
    at _stringify (runtime.js:97)
    at _stringify (runtime.js:103)
    at Runtime.push../node_modules/messageformat/lib/runtime.js.Runtime.toString (runtime.js:118)
    at MessageFormat.push../node_modules/messageformat/lib/messageformat.js.MessageFormat.compile (messageformat.js:343)
    at TranslateMessageFormatCompiler.push../node_modules/ngx-translate-messageformat-compiler/esm5/ngx-translate-messageformat-compiler.js.TranslateMessageFormatCompiler.compileTranslations (ngx-translate-messageformat-compiler.js:25)
```

- if I provide the translations with a file where the language code has 2 characters (e.g. en.json) - it works fine for both non-ICU and ICU translations.

Here is the reproduction of the "bug" (it also exists without using Angular, so that would probably mean the issue lies in messageformat, not in Angular libraries): https://stackblitz.com/edit/typescript-cqpntn

Is it by any chance a desired behavior?

Please let me know if you need any more information for the potential investigation.

Thank you for any feedback!

**Comment by lephyrus** [comment]
@mmanista I've just released a workaround for this in ngx-translate-messageformat-compiler. You can now configure the locales you want to use, in which case "composed" locales work fine.

Here's @eemeli's explanation of the underlying issue: https://github.com/lephyrus/ngx-translate-messageformat-compiler/pull/29#issuecomment-410052125

I can confirm that the error crops up under the following conditions:
- `MessageFormat` is instantiated without passing any locales
- `compile()` is called with a message that actually contains "advanced" ICU syntax
- `compile()` is called with a "composed" locale as the second argument

**Comment by lephyrus** [comment]
Ha, I've just seen that it's been fixed already a week ago. 👏 
https://github.com/messageformat/messageformat/commit/b563d80c4230162c4a609470204686ef83ff47c0

**Comment by mmanista** [comment]
Worked like a charm, thank you so much!

Closing

**Comment by arobinson** [comment]
I'm not seeing this as fixed. Using the test code here, I tried the following:
`var mf = new MessageFormat();
// ERROR:
mf.compile({"years": "{count, plural, one{Year} other{Years}}"}, 'en-x-test');`

This will work though:
`var mf = new MessageFormat(['en','en-x-test']);
mf.compile({"years": "{count, plural, one{Year} other{Years}}"}, 'en-x-test');`

The problem is not fixed when not passing locales to the MessageFormat constructor.
