### ISSUE TITLE
How domain or context is supported?

### ISSUE THREAD

**Issue by JSteunou** [messageformat/messageformat#207]
Comparing this format with gettext (I'm a Jed user, kudos to @SlexAxton :1st_place_medal: ) how a domain or at least a context can be used for 2 similar sentences that might be translated in a different way in other languages.

Naive example : if my default language is english and I have  the word `top` in my code, it could mean a filter like `top 10` or a direction, like opposed to bottom. In French we would say `top` for the 1st case but `haut` for the 2nd.

How to achieve the same than pgettext or dgettext with messageformat in order to give a hint to the translator?

**Comment by SlexAxton** [comment]
I think in general you’d just give them (and nearly everything) a unique
key. Since we don’t use messages as keys, this tends to work just fine in
my experience.

I think in the world of translation vendors, they’re all using translation
memory systems to dedupe things, so it doesn’t buy all that much to share
simple strings like “top.”

This isn’t true for everything. Long disclaimers or product names can be
pretty safely shared, but I wouldn’t call it a priority.

Kind of a non-answer, but hopefully that makes sense?

**Comment by JSteunou** [comment]
I understand you but unfortunately that does not answer this use case entirely or just put in evidence a hole in messageformat.

When you are using message (with a base in english for example) as message id instead of a key (which could be difficult to translate without the message, but that the eternal key versus message as message id debate) when using gettext with pgettext, the translator see *top* once with a certain hint then *top* a second time with another hint in the catalog. Migrating to messageformat, I see no easy way to add this hint, and if omit, *top* will just appear once in the catalog.

If I understand well the only way to achieve this with messageformat is to shift and use a key as message id?

**Comment by eemeli** [comment]
Does it help that messageformat supports hierarchical structures for messages? This means that you could have something like this as your data:
```json
{
  "filter": {
    "top": "top"
  },
  "direction": {
    "top": "haut"
  }
}
```

**Comment by SlexAxton** [comment]
Ah, yea. We require a description for every single message in our code
base. A “message descriptor” for us is a key, a description, and a message.
If it is missing any of the 3, we throw a type error.

On top of that, I’d encourage the use of a translation system with
in-context support. You can load up your app and click on any message and
see which key it is, etc. This has been by far the best win for our
translators of getting context right.

**Comment by JSteunou** [comment]
Thank you both, that is exactly what I needed ! I will try this.
