### ISSUE TITLE
Support for nested variables?

### ISSUE THREAD

**Issue by ieugen** [messageformat/messageformat#217]
Hello,

This might sound strange but does messageformat support nested variable names? 

What I would like is to have something like: 

messageFormat('Hello {account.displayName}', { account: { displayName: "Evil Corp"}  } ) . 

The advantages are that I can expose to users a set of variable names that are available in their templates and they can use them. 

Regards,

**Comment by eemeli** [comment]
Unfortunately that isn't supported, as the `.` character isn't allowed as an argument name character.

To work around this, you could flatten your input object and use e.g. `_` as a separator:

```js
function smoosh(obj, res = {}, prefix) {
  for (const k of Object.keys(obj)) {
    const key = prefix ? `${prefix}_${k}` : k
    const val = obj[k]
    if (typeof val === 'object') smoosh(val, res, key)
    else res[key] = val
  }
  return res
}

const mf = new MessageFormat()
const msg = mf.compile('Hello {account_displayName}') // note _ separator
const obj = { account: { displayName: "Evil Corp"} }

msg(smoosh(obj)) // 'Hello Evil Corp'
```

**Comment by MatthiasKunnen** [comment]
@eemeli, what forbids the `.` character? ICU standard or the implementation? Or something else entirely?

**Comment by eemeli** [comment]
The limitation is coming from the [ICU MessageFormat spec](https://unicode-org.github.io/icu-docs/apidoc/released/icu4j/com/ibm/icu/text/MessageFormat.html), as `argName` must match `[^[[:Pattern_Syntax:][:Pattern_White_Space:]]]+`, and `.` is included in the `Pattern_Syntax` character group.
