### ISSUE TITLE
Intl format constructors should be cached in compiled output

### ISSUE THREAD

**Issue by germanftorres** [messageformat/messageformat#224]
Hi,

When the ICU message format includes a formatter like duration, date, number the performance degrades when translating a lot of messages in one page. I guess the Intl.NumberFormat or Intl.DateTimeFormat should be cached and reused  as they are expensive to [instantiate](https://github.com/yahoo/intl-format-cache)

This is the current code included in the compiled MessageFormat. Note that each call to apply a number format is effectively instantiating a new Intl formatter.
````
var fmt = {
  number: function (value, lc, arg) {
    var a = arg && arg.split(':') || []
    var opt = {
      integer: { maximumFractionDigits: 0 },
      percent: { style: 'percent' },
      currency: {
        style: 'currency',
        currency: a[1] && a[1].trim() || "USD",
        minimumFractionDigits: 2,
        maximumFractionDigits: 2
      }
    }
    return new Intl.NumberFormat(lc, opt[a[0]] || {}).format(value)
  }
````
Maybe this  code could benefit from a cache like here 
https://github.com/yahoo/intl-format-cache

**Comment by eemeli** [comment]
You're right, that would be a decent optimisation. A PR on this would be welcome.

**Comment by eemeli** [comment]
Realised that with the updated runtime, this was a rather easy fix.
