### ISSUE TITLE
# in select no longer resolves numbers

### ISSUE THREAD

**Issue by sambodo7** [messageformat/messageformat#225]
I an older version we where using # within a select would resolve to a number now it just outputs the #

`const MessageFormat = require('messageformat')

const msgSrc = `Here it is {foo, select, bar {word} other {number #}}`
const mf = new MessageFormat('en')
const msg = mf.compile(msgSrc)

console.log(msg({foo: "bar"}))  //latest - Here it is word             v0.8 -  Here it is word
console.log(msg({foo: 2 }))       //latest - Here it is number #      v0.8 - Here it is number 2
console.log(msg({foo: "2"}))     //latest - Here it is number #      v0.8 - Here it is number 2`

**Comment by SlexAxton** [comment]
I am fairly certain this came out of the parser in a major version change because it's not valid messageformat inside of a selectFormat block, only a pluralFormat block.

**Comment by eemeli** [comment]
Yeah, this got fixed in the 1.0 release back in 2016. The discussion on that is mostly on PR #138. @sambodo7, I'm afraid you'll need to fix your source messages to account for this: The `#` character is a valid shorthand only for a `plural` variable.
