### ISSUE TITLE
Getting unexpected output with nested messages

### ISSUE THREAD

**Issue by evandervalk** [messageformat/messageformat#226]
Consider the following test.

```
    it('nested', () => {
      const msg = mf.compile('{HOURS, plural, =0 {{MINUTES, plural, =0 {{SECONDS, plural, =0 {} other {#s}}} other {#m {SECONDS}s}}} other {#h {MINUTES}m {SECONDS}s}}');
      const data = { 
        HOURS: 1,
        MINUTES: 10,
        SECONDS: 15
      };
      expect(msg(data)).to.match(/^1h 10m 15s/);
    });
```

I get the following error: `Error: expected '#h 10m 15s' to match /^1h 10m 15s/`.

As you can see from the unit-test result it prints `#h 10m 15s` which is incorrect.

Can someone confirm this is a bug with the message parsing or is there something else at play here.

Kinds regards,
Erik

**Comment by eemeli** [comment]
That definitely looks like a bug, which tbh is really rather suprising. But a bug nevertheless.

**Comment by eemeli** [comment]
The `inPlural` state was being tracked by a single boolean variable, which ended up resetting when exiting the inner plural and making `#` non-special in the subsequent outer "other" case. I fixed this by using a stack of booleans to track the state instead. Also added your test case to our test suite.

Should get around sometime soon to publishing new releases of the packages as well.
