### ISSUE TITLE
Compact Decimal Format

### ISSUE THREAD

**Issue by snewcomer** [messageformat/messageformat#229]
👋 I worked on a solution a few months ago to add short number formatting to a library similar to this and have this working in some applications.  

https://github.com/snewcomer/cldr-compact-number

I'm not familiar with the internals of this library so I wanted to float the idea by you if you thought it might be a good addition.

Convert numbers like -
- `101234` to `101,1` mil in Espanol
- `101234` to `10.1万` in Japanese

https://github.com/ember-intl/intl-messageformat/pull/1

**Comment by SlexAxton** [comment]
Definitely a good idea to mix these libraries, but don’t know if we should include them together by default.

We afford for adding custom short formatters in user-land. Perhaps we can document/ship a configuration that ties your lib to a short formatter in ours?

**Comment by eemeli** [comment]
With the monorepo structure, it might make sense to split out the formatters into their own package, and to by default only import the ones that are actually part of the [spec](http://icu-project.org/apiref/icu4j/com/ibm/icu/text/MessageFormat.html). Then `compact` could be implemented as a custom argStyle of `number`.

**Comment by snewcomer** [comment]
^^ I like that idea.  Lmk if/when a repo for `compact` is created and I can start working on it.  Would be happy to help porting over the other formatters as well.

**Comment by eemeli** [comment]
@snewcomer This repo now includes `packages/formatters/`, which is the source for the soon-to-be-published `messageformat-formatters` package. Atm it just contains the default formatters; once `compact` or something like it is also included, we can work on the API for using them.

**Comment by snewcomer** [comment]
@eemeli Perfect!  Yeah I've been tracking the work that has gone in! 👍  Hopefully within the next month I'll be able to work on this.

**Comment by snewcomer** [comment]
@eemeli I'm not sure of an easy path to integrating compact number formatting.  It has a dependency on a large data set to be put into memory in order to translate a number to its compact equivalent.  What we do on a few ember projects is at build time generate a file based on the user's supported languages and then hydrate the locale data at runtime.

My initial reaction is this may be too large of a task/outside the bounds to implement for this library.  Let me know what you think.

https://github.com/unicode-cldr/cldr-numbers-full

**Comment by eemeli** [comment]
@snewcomer Actually that sounds rather close to what messageformat is already doing when it compiles stringifiable output. That output includes plural category functions for just the included plurals.

If you were to put together a draft PR to achieve what you want without considering the efficiency concerns, I'd be happy to work with you at making it suitable for release.

**Comment by eemeli** [comment]
This issue has languished here for ages, but with #313 it should _finally_ become easy to provide a solution for this. As a first-pass solution, something like this seems to work:

```js
// compact.js
import { compactFormat } from 'cldr-compact-number';

const localeData = {};

export const compact = (value, locale, options = {}) =>
  compactFormat(value, locale, localeData, options);
```

```js
// rollup.config.js
import alias from '@rollup/plugin-alias';
import messageformat from 'rollup-plugin-messageformat';
import { compact } from './compact';

const customFormatters = {
  compact: { formatter: compact, arg: 'options', id: 'compact', module: '~compact' }
};

export default {
  input: 'src/main.js',
  output: { dir: 'dist' },
  plugins: [
    alias({ entries: { '~compact': './compact.js' } }),
    messageformat({ customFormatters, locales: ['en'] })
  ]
};
```

```properties
# src/messages.properties
compact = Only {n, compact, significantDigits: 1}
```

```js
// src/main.js
import messages from './messages.properties';

console.log(messages.compact({ n: 424567546 }));
```

When compiled, that produces this bundle:

```js
// dist/main.js
import { compactFormat } from 'cldr-compact-number';

const localeData = {};

const compact = (value, locale, options = {}) =>
  compactFormat(value, locale, localeData, options);

var messages = {
  compact: (d) => "Only " + compact(d.n, "en", {"significantDigits":1})
};

console.log(messages.compact({ n: 424567546 }));
```

And that, when executed, prints out this:
```
Only 424.6M
```
