### ISSUE TITLE
v2.1.0: uppercased formatters are broken

### ISSUE THREAD

**Issue by MatissJanis** [messageformat/messageformat#230]
Hey,

With the new release of v2.1.0 uppercased formatters are broken.

Here's code sample: 
```javascript
const MessageFormat = require('messageformat');
const mf = new MessageFormat('en-GB');
mf.addFormatters({
  upcase: function(v) {
    return v.toUpperCase();
  },
  
  asUpcase: function(v) {
    return v.toUpperCase();
  },
});

// Works
const message = mf.compile('This is {VAR, upcase}.');
console.log(message({ VAR: 'test' }));


// Breaks
try {
  const brokenMessage = mf.compile('This is {VAR, asUpcase}.');
  console.log(brokenMessage({ VAR: 'test' }));
} catch (e) {
  console.error('Error with uppercased formatter name:', e);
}
```

**Comment by eemeli** [comment]
You're right. Custom function names are currently required to be lowercase, thanks to [this change](https://github.com/messageformat/parser/pull/8/commits/8e5e648b7bf9d06162eeaceefeb560f0e685de3c), which was a part of messageformat/parser#8. And that's probably wrong, especially as it's not documented.

IIRC, that may have been a bit of a shortcut to make sure that [this test](https://github.com/messageformat/messageformat/blob/71b84002b95e047a12ebe69bcaa1a1f7f986e70e/packages/parser/test.js#L172) doesn't fail, i.e. to prevent defining a custom formatter like `Select`. Which might in hindsight be a bit too much pre-emptive optimisation and coddling.

The right thing to do here would probably be to relax the parser's check, allowing non-lowercase chars in formatter identifiers. The alternative would be to keep and document the current functionality, while making sure that the error is thrown much earlier, i.e. when trying to set the formatter in the first place -- and that would be tricky with the [published API](https://messageformat.github.io/messageformat/page-guide#toc11__anchor) of adding cormatters directly to the `MessageFormat.formatters` object.

**Comment by MatissJanis** [comment]
Thanks!

**Comment by eemeli** [comment]
The overlap check is now a bit more complicated, but also more appropriate. I had forgotten that e.g. `Select` needs to be prevented at this level to make sure that a MessageFormat string with that will throw a build-time error, as it's almost certainly a typo of `select`.

**Comment by MatissJanis** [comment]
Any ETA when a new version will be released with this fix?
