### ISSUE TITLE
Support date format skeleton

### ISSUE THREAD

**Issue by superCarton** [messageformat/messageformat#235]
Hi guys,

According to the documentation, messageformat is only supporting parameters `short, default, long , or full` for the date. In [ICU message format](http://icu-project.org/apiref/icu4j/com/ibm/icu/text/MessageFormat.html), there another "free" parameter, called argStyleText. It is using skeleton `::`, which allow much more flexibility for date formats. 
The usage is the following [ICU date](http://icu-project.org/apiref/icu4c/classSimpleDateFormat.html):
```
{dateParameter, date, ::dMMMM}
```
Is it planned for future versions to integrate sketelons? Or would you accept contributions for it?

Cheers!

**Comment by eemeli** [comment]
Sure, a PR for this would be welcome. The [current implementation](../blob/master/packages/formatters/lib/date.js) manages to stay rather lightweight on account of relying on [Date#toLocaleDateString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString), but expanding compatibility is (nearly) always a good thing.

**Comment by superCarton** [comment]
Good to hear that! I will work on it as my need is to be quite flexible for date formats, and I will come back to you with a PR ;)

**Comment by iamahuman** [comment]
Globalize.js supports this, but ironically it depends on this project yet doesn't set up a custom formatter to use its date module.

**Comment by eemeli** [comment]
In semi-related news, I've been recently working on a number-format skeleton parser that can provide a formatter using `Intl.NumberFormat`. I'll shortly release that in a separate repo to start with, as I ended up writing it in TS. Might end up looking at the date-format skeleton as well.

**Comment by ray007** [comment]
Shameless plug: since I also needed ICU patterns and didn't want to deal with all the CLDR data, I've made [simple_dt.js](https://github.com/ray007/simple_dt.js).

**Comment by eemeli** [comment]
Date skeleton support was added in #279.
