### ISSUE TITLE
Unable to minify v2.2.0 using Uglifier

### ISSUE THREAD

**Issue by davidchin** [messageformat/messageformat#237]
I'm unable to run Uglifier after upgrading `messageformat`from v2.1.0 to v2.2.0. I had a look at the changelog. It seems there are some changes in the build process recently. I wonder if these changes cause the problem. As you might already know, Uglifier can only parse ES5 files. But the latest version no longer produces ES5 files (files in `lib` folder which `package.json` points to). So when I run Uglifier, I get the following error:

```sh
Message:
    vendor.min.js from UglifyJs
Unexpected token: keyword «const» [./node_modules/source-map-loader!./node_modules/messageformat/lib/utils.js:9,0][vendor.min.js:31768,0]
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

It would be nice if `main` field of `package.json` points to ES5 files so that the package can still work with Uglifier. Is there a particular reason why the output has changed?

**Comment by eemeli** [comment]
The `messageformat/package.json` browser field was wrong. I've (hopefully) fixed it with 341bc6f, and will push out a patch release once I verify that the fix is valid.

**Comment by MatissJanis** [comment]
Any ETA for release of this fix?

**Comment by eemeli** [comment]
Messageformat 2.2.1 is out now with this fix.
