### ISSUE TITLE
IE11 stopped working with messageformat 2.2.0

### ISSUE THREAD

**Issue by rsheptolut** [messageformat/messageformat#238]
After updating `messageformat` from `2.0.4` to `2.2.0` in my Angular 7 project (built with Angular CLI), the application stopped opening in IE. Works fine in Chrome or Firefox, but IE11 barks at `class Compiler` syntax. Probably doesn't know what `class` is?

Was IE11 support intentionally dropped or is it a regression? Maybe there's something wrong with my build config (which I don't think I touched after generating with the Angular CLI), as I thought TypeScript should be dumbing everything down for lesser browsers, and the rest of the class-heavy type script code works fine (as did `messageformat 2.0.4`). Let me know if you need any extra info.

**Comment by eemeli** [comment]
This is a regression, and almost certainly the same issue as in #237 (continuing there). IE11 should definitely work, and we now have Selenium tests for that included in our CI setup.
