### ISSUE TITLE
Angular production build stuck after 2.2.1 release

### ISSUE THREAD

**Issue by frankie567** [messageformat/messageformat#239]
I have an Angular project where I use `messageformat` (along with [`ngx-translate-messageformat-compiler`](https://github.com/lephyrus/ngx-translate-messageformat-compiler#readme)) for localization. I just upgraded to 2.2.1 version today and realized that the production build is getting stuck when handling `messageformat.js`:

```
49% building 328/330 modules 2 active ..._modules/messageformat/messageformat.js
```

After reaching that point, it never ends.

I suspect it comes from [this change](https://github.com/messageformat/messageformat/commit/341bc6f8e58216dc1f850c2a9c06da35d99d8de7). When I manually change the `browser` value from `messageformat.js` to `index.js`, it works flawlessly.

It also works when disabling AOT optimization. I'm not quite sure then who's "fault" is it, but I thought maybe you would have some insights about this.

Cheers!

**Comment by eemeli** [comment]
Any chance of getting a minimal or at least smaller sample that triggers this, or at least some more verbose logging of what's causing the issue?

**Comment by frankie567** [comment]
Sure, here is a minimal Angular project reproducing the issue: https://github.com/frankie567/messageformat-issue-239

It's probably something around the package.json `browser` property, source maps generation and AOT optimizations. I've gathered a number of cases playing with the different configurations.

Thank you for your help!

**Comment by eemeli** [comment]
I've traced this to the wrap-enums build optimizer, and reported it to the angular-cli repo. I'm pretty sure this is not our bug, but theirs. Happy to keep this open for now to track whether it gets fixed there.

**Comment by frankie567** [comment]
Thank you for this thorough analysis, that's impressive 👍

**Comment by artuska** [comment]
'Cmon, just provide two files:

    messageformat.js
    messageformat.min.js

Do not provide minified version in `messageformat.js` file.

**Comment by eemeli** [comment]
@artuska It's not so simple. Effectively, you're asking for a breaking change in this library in order to work around a bug in a dependency of a completely separate project, which has apparently already been fixed in the original dependency.

**Comment by vtolstov** [comment]
i have this issue too. i'm upgrade messageformat to 2.3.0 and build stuck

**Comment by artuska** [comment]
2.3.0 — still actual

**Comment by frankie567** [comment]
With the release of Angular 8.2.0, the default TypeScript compiler version is now 3.5+. As stated in issue angular/angular-cli#14505, this new version of TypeScript indeed fixes the issue.

**Comment by eemeli** [comment]
Closing as fixed upstream.
