### ISSUE TITLE
Problem with Component Interpolation and V18n

### ISSUE THREAD

**Issue by FSchubert92** [messageformat/messageformat#241]
We have an Issue concerning the message compiler. 
When trying to use v18n component interpolation with VueJs this does not work correctly due to the compile function which is returning a single string.
the function returns an `[object Object]` which shows us that r has elements of `VNodes` of Vue.
We were able to  fix the problem by using the following line in the message compiler, which returns an array which we can then use.
`return 'function(d) { return [' + (r.join(', ') || '""') + ']; }';`
Is it possible to add a configuration which allows us to determine whether we get a string or an array back by the function?

**Comment by eemeli** [comment]
It might be a good idea to give a minimal example of the setup that produces this error? As is, I'm not very familiar with Vue and I'm not sure what's happening just based on your description, or what exactly you might be looking for.

**Comment by FSchubert92** [comment]
Sorry for the late reply. 
Since the issue is a little hard to describe by words, I recreated  the setup in a smaller scale in Codesandbox. 
 [Here is the link](https://codesandbox.io/embed/reproduction-vuei18n-component-interpoliation-lir08)

As you see, we try to use the Vi18n Component Interpolation as it is described [here](https://kazupon.github.io/vue-i18n/guide/interpolation.html). 

Like I already said, we were able to identify line 40 of the compiler.js as the one causing the problem, since it injects `VNodes` Elements.

**Comment by eemeli** [comment]
Okay, I think I now see what you're getting at. At the moment with your code the messageformat compiler is providing you with this output function:
```js
function(d) { return "I am a string and I would like to have something " + d.here; }
```

while what you'd like is this:
```js
function(d) { return ["I am a string and I would like to have something ", d.here]; }
```

That's probably rather doable, actually. It's not just a matter of fixing the top-level concatenation that you identified, but also e.g. that of plural selectors. Would it be acceptable in your usage that the output then might have arrays within arrays in its output?

**Comment by FSchubert92** [comment]
That would be okay for us!
