### ISSUE TITLE
Should we support shorthand numbers inside of a simpleArg?

### ISSUE THREAD

**Issue by SlexAxton** [messageformat/messageformat#246]
I don't know if this is cross-lib-compatible, but one thing I dislike is having to retype the plural variables in order to format them.

Any time I want to use `#` in a `pluralFormat` I also want to format that number, so `#` becomes useless.

Not suggesting we should yet, but wondering your thoughts, @eemeli on allowing:

```
// Old unformatted numbers
{numTotal, plural, one{# result} other{# results}}

// Old formatted numbers
{numTotal, plural, one{{numTotal, number} result} other{{numTotal, number} results}}

// Possible mashup
{numTotal, plural, one{{#, number} result} other{{#, number} results}}
```

**Comment by SlexAxton** [comment]
another option is to allow a formatter for the shorthand per instance

```jsx
new MessageFormat('en-US', {
  // didn't actually test or think about this very hard, just spitballing
  shorthandFormatter: (x) => new Intl.NumberFormat('en-US').format(x)
})

// Then this just auto-calls that formatter
{numTotal, plural, one{# result} other{# results}}

```

**Comment by eemeli** [comment]
That's actually a mistake on our part, we should totally format `#` by default. Here's a [direct quote](http://icu-project.org/apiref/icu4j/com/ibm/icu/text/PluralFormat.html) spelling it out:
>An unquoted pound sign (#) in the selected sub-message itself (i.e., outside of arguments nested in the sub-message) is replaced by the input number minus the offset. The number-minus-offset value is formatted using a `NumberFormat` for the `PluralFormat`'s locale. If you need special number formatting, you have to use a `MessageFormat` and explicitly specify a `NumberFormat` argument.

We should fix this as a part of the major-version bump.

**Comment by eemeli** [comment]
On the other hand, I don't think we should add spec-breaking syntax for this. I think if you need non-default formatting, then it's okay to continue requiring you to be explicit about it.
