### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by joeyhub** [messageformat/messageformat#251]
There's no getting started documentation for this.

What do I require to get what?

Libraries + data?

How do I wire these together?

**Comment by eemeli** [comment]
Have you looked at the documentation site? It should have the answers that you seek.

https://messageformat.github.io/

**Comment by joeyhub** [comment]
It has some basic documentation which isn't particularly helpful in explaining how things fit together. If someone already knows of ICU it's just copy and paste snippets.

The main problem is working out how to package it into a small foot print for the browser which is a particular sticking point with ICU especially if there's some desire to include data sets.

On this front there's mention of webpack and the loader (is a bit noisy to me as loading is really easy to DIY and webpack can be a bit overly complex).

Key things that could be clearer:

* There's a number of packages. Many are just noise, IE, loader, cli, etc where as others represent portions of the library. There are things not clear on wiring those together, IE, I can assume that formatters is meant to be plugged into addFormatters though it's not really entirely made clear explicitly how to assemble everything.
* Not clear how the ICU data works (not userspace translations). For example, utilising the browsers INTL for formatting dates, numbers, plural rules, etc? How much of it's own data does it need and how complete is that? It mentions having CLDR but also a small footprint and some missing formatters so there seems to be something missing there.
* It also mentions supporting all the languages but not how language support can be varied to change the footprint. Does it actually mean it supports all of them if the underlying libraries used has those?
* What about the need for polyfills or dependent libs?
* Mentions a few things like ordinal are missing but not if these can be acquired.
* How faithful is it to ICU / Intl? I tend to want it to match PHP which I usually have built with full ICU.

Small typo in the docs...

> Obviously this is a slightly contribed example

**Comment by Alino** [comment]
How can I convert ICU to JSON and vice versa? Does this library do this?
How can I convert English locale ICU plural message into different locale for example Czech?
