### ISSUE TITLE
Wrong typescript typing for MessageFormat.compile

### ISSUE THREAD

**Issue by lukasbalaz** [messageformat/messageformat#252]
https://github.com/messageformat/messageformat/blob/58e379d5991a80854c76a4639b9c60409f9195ce/packages/messageformat/index.d.ts#L2

https://github.com/messageformat/messageformat/blob/58e379d5991a80854c76a4639b9c60409f9195ce/packages/messageformat/index.d.ts#L22-L25

When `SrcMessage` is an object, the function returns an object, not a `Msg`.

**Comment by eemeli** [comment]
A PR on this would be welcome.
