### ISSUE TITLE
Since 2.2.1 this library started to use getters, breaking compatibility with IE6/8

### ISSUE THREAD

**Issue by sormy** [messageformat/messageformat#260]
Since 2.2.1 this library started to use getters in build artifacts.
It is just one reference but it breaks compatibility with IE6/7.
Version 2.2.0 is fine.

```
Object.defineProperty(t,r,{enumerable:!0,get:n})}
```

I did not find any getters in source code so it looks like something that is introduced by bundler.

PS: Yes, 2019, IE6/7 is still alive on Windows CE 7 platform.

**Comment by eemeli** [comment]
This is almost certainly due to the refactor for 2.2.0 of the source as ES6, and then starting to use Webpack & Babel for transpiling the source.

I would recommend that you either stick with 2.1.0 if it works for you, figure out how to do a custom ES3 build from the source files, or refactor your code so that the message compilation is a part of your build (and hence takes place in a different JS environment), rather than remaining as a runtime activity.

If you do end up going for a custom build, and it turns out that the changes required are not onerous, it might be of interest to apply that to our published artifacts.

**Comment by sormy** [comment]
2.2.0 is fine, something has changed in 2.2.1. It seems like webpack is adding some wrapping code that is using getters and getters are not polyfillable or transpillable even with custom build toolchain that we use (rollup + babel + preset-env targeting ie7 + core-js polyfills)

**Comment by sormy** [comment]
And I guess the easiest solution is to just add `"module": "./src/messageformat.js"` into `package.json` so rollup/webpack bundler can automatically pull ESM version instead of precompiled file.

**Comment by sormy** [comment]
This is how webpack@4 is pulling getters:

```js
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, { enumerable: true, get: getter });
/******/ 		}
/******/ 	};
```

Related: https://github.com/webpack/webpack/issues/6979

**Comment by eemeli** [comment]
I think changing build systems just to maintain support for IE8 would be a bit too much to ask. Are there other benefits over Webpack 4 that you believe Rollup would bring us?

At the moment `messageformat` is packaged in two different ways:
1. CommonJS, transpiled with a Node 6.5.0 target
2. UMD, transpiled with a Browserslist target of `> 0.5%, last 2 versions, Firefox ESR, not dead`

The first of these is provided at `"main"`, the second from the `"browser"` endpoint. The change in 2.2.1 that's probably triggering this for you was fixing that browser endpoint. Have you tried configuring your bundler to ignore the browser field? As you're targeting rather obsolete browsers, I suspect you're needing to transpile your dependencies anyway?

For an alternative approach, as a part of the ongoing v3 update, we'll probably want to consider including an ES module output with `.mjs` extensions, given that all of our dependencies already support that. Whether that would be a Node- or browser-targeting target I can't really say yet.

**Comment by sormy** [comment]
Ok, resolving given that explicit resolution to `index.js` helped to solve the issue.
