### ISSUE TITLE
How to escape '/' for `SelectFormat`

### ISSUE THREAD

**Issue by tomstumshais** [messageformat/messageformat#268]
Hey!

Help wanted! 
Don't know if this is an issue at all, just posting there, maybe someone can help me with this.

My `messageFormat` string looks like this: `{foo, select, one/two{1-2} other{3}}`, but `messageFormat` parser throws error because of `/` usage in `select` value (`one/two`).

I have tried, but not working:
```
{foo, select, one'/'two{1-2} other{3}}
{foo, select, 'one/two'{1-2} other{3}}
```

Any ideas?

Posted question in SO too.
https://stackoverflow.com/questions/58990596/how-to-escape-for-selectformat-with-messageformat-js

Thanks in advance!

**Comment by eemeli** [comment]
Unfortunately, that's not possible. `/` belongs in the [Pattern_Syntax](https://chars.suikawiki.org/set/%24unicode%3APattern_Syntax) set of characters, and the [expression for select keywords](https://unicode-org.github.io/icu-docs/apidoc/released/icu4j/com/ibm/icu/text/SelectFormat.html) is `[^[[:Pattern_Syntax:][:Pattern_White_Space:]]]+`, i.e. it explicitly excludes that character from being usable in a keyword. I would recommend using something like `one_two` instead.
