### ISSUE TITLE
command line tool fails on windows

### ISSUE THREAD

**Issue by ray007** [messageformat/messageformat#270]
I tried to use the command line to to create functions from my json files as written in the docs, but I got an error:
```
$ npx messageformat --locale=en,de src\locales\
C:\rtc-sandbox\ws_rb_lweb\lweb\src\lweb_802\src\lweb900views\node_modules\messageformat\lib\compiler.js:58
        const pl = plurals[key] || plural;
                          ^

TypeError: Cannot read property '802/src/lweb900views/src/locales/de' of undefined
    at Compiler.compile (C:\rtc-sandbox\ws_rb_lweb\lweb\src\lweb_802\src\lweb900views\node_modules\messageformat\lib\compiler.js:58:27)
    at MessageFormat.compile (C:\rtc-sandbox\ws_rb_lweb\lweb\src\lweb_802\src\lweb900views\node_modules\messageformat\lib\messageformat.js:176:41)
    at Object.<anonymous> (C:\rtc-sandbox\ws_rb_lweb\lweb\src\lweb_802\src\lweb900views\node_modules\messageformat-cli\messageformat.js:91:19)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```
I tried several variations with and without single- or double-quotes around the directory name, `/` or `\` as path separator, and also the `npm run ...` variant with config in `package.json`, the result stays the same.
Didn't try on other platforms, but given the `TypeError`, could the `"_"` character in the path be a problem?

**Comment by eemeli** [comment]
Could you specify what version of `messageformat` and `messageformat-cli` this happened with? It looks like there's probably a problem with the delimiters handlings. You may also want to play around with [that option](https://github.com/messageformat/messageformat/blob/messageformat%402.3.0/packages/cli/README.md#--delimiters)?

**Comment by ray007** [comment]
Setting delimiters seemed to have been part of the problem (why is `_` part of then?), but not all of it.

Versions:
```
$ npm install messageformat@next messageformat-cli
+ messageformat@3.0.0-beta.1
+ messageformat-cli@2.1.1
```

Interestingly enough a
```
npm install messageformat@2.x
```
fixed the problem, but now I don't have the `@next` version of `messageformat` installed anymore.

**Comment by ray007** [comment]
Maybe I'm misunderstanding the docs, or it's a problem of now having the 2.x version of `messageformat` instead of 3.x.

I specify `--locale=en,de`, but the resulting script only gets a function for `en`, none for `de`.
The `en` function consequently is used for all languages.

I would also have expected only `en.json` and `de.json` would be processed, but the other 4 (currently untranslated) locales in the directory are also included in the resulting js-file.

And is there an option to get the result keyed only by language (locale) instead of the full path to the json-file without extension?

Hmm, maybe I should write my own script with `MessageFormat.compile()`...

**Comment by eemeli** [comment]
Yeah, using v2 cli with v3 core is completely untested. The module compiler API changes a bit in that transition.

The cli attempts to make a minimal set of assumptions without adding too much complexity, as the layout on disk and the desired output is highly variable between users. Writing your own build script should be pretty easy, and allow you to build exactly the modules you want. I would highly recommend using the v3 beta for that.

**Comment by ray007** [comment]
I just followed the docs from the `README`, so maybe there's an `@next` missing?

**Comment by ray007** [comment]
Update: installing both modules and moving the input parameter to the start makes things work.

But the keys for the exported output object are still the whole paths to the input files without extensions.
That I can fix with a replace on the output file.

But the line
```javascript
import { en } from 'messageformat-runtime/lib/cardinals';
```
should probably have an imported entry for each locale.

And the german plural format uses the english number format:
```javascript
"events-num": function(d) { return plural(d.n, 0, en, { one: number("en", d.n, 0) + " Ereignis", other: number("en", d.n, 0) + " Ereignisse" }); },
```

Specifying only 1 locale on the command line imports the correct one, but still reads all json files found in the directory.
