### ISSUE TITLE
Wrong format for RTL languages

### ISSUE THREAD

**Issue by anteburazer** [messageformat/messageformat#271]
I have use case where app supports RTL languages and I'm trying to format the message when system language is set to e.g. Arabic.

This is the message format:
`"{gender, select, female{{personName} تفاعلت مع رسالتك.} male{{personName} تفاعل مع رسالتك.} other{{personName} تفاعل مع رسالتك.}}"`

Wherever I set the `personName` variable (before or after Arabic text) it's always displayed at the beginning, which is wrong.
Although, if I set the variable in the middle of the string it's displayed properly.

**Comment by eemeli** [comment]
Is this happening with [bi-directional support](https://messageformat.github.io/messageformat/MessageFormat#setBiDiSupport__anchor) enabled, or otherwise?

**Comment by anteburazer** [comment]
Didn't notice that option. When I set it to `true` it works as expected. Thank you for the response.

**Comment by eemeli** [comment]
Out of interest, were your `personName` strings in an LTR or RTL script? Given that MessageFormat markup itself is LTR, I would not be entirely surprised if this was causing an issue even with content being entirely RTL.

**Comment by anteburazer** [comment]
`personName` was in LTR format but I didn't test it with RTL names to see if that would fix the problem.

**Comment by eemeli** [comment]
In that case I'm going to close this as answered. In case it turns out that bi-directional support is needed for any/all RTL cases, we can add a detector for that.
