### ISSUE TITLE
Update latest stable version in releases

### ISSUE THREAD

**Issue by mrsarm** [messageformat/messageformat#286]
The last version pointed at https://www.npmjs.com/package/messageformat is 2.3.0 , but the latest pointed in Github is https://github.com/messageformat/messageformat/releases/latest (2.0.5), not a big deal, but it would be good if you fix it, the 2.3.0 does not look like even tagged, and seen the 2.0.5 in the home page at Github makes the project to look outdated, which is not.

**Comment by eemeli** [comment]
Thanks, good catch. That's when we switched to a monorepo, with Lerna tagging releases differently. Added the missing releases.
