### ISSUE TITLE
Compilation failure on parenthesis not used for variables

### ISSUE THREAD

**Issue by siilike** [messageformat/messageformat#293]
The parser currently throws an exception on a stray parenthesis, for example:
```
Hello, {name}!
```
works fine, but
```
Hello, {{name}!
```
throws an exception:
```
Expected identifier but "{" found.
```

**Comment by eemeli** [comment]
That's right? I mean, this is expected behaviour as that isn't a valid message.

What did you expect to happen instead?

**Comment by eemeli** [comment]
Closing as answered.
