### ISSUE TITLE
How to have multiple json files, one for each language?

### ISSUE THREAD

**Issue by gamedevsam** [messageformat/messageformat#302]
I would like to have separate files for different languages, ex:

messages_en.json
messages_es.json
...

But it seems this loader expects all languages to be present in the same json under different language keys, ex:

```
{
    "en": {
        ...
    },
    "es": {
        ...
    }
}
```

Any suggestions on how I can keep the language files separate?

**Comment by eemeli** [comment]
Your separate-file usage should "just work", and I even have production code myself that's using a very similar naming pattern. Could you provide an example of code & config where you're getting results that are different from your expectations? Also, with what versions is this occurring?

**Comment by gamedevsam** [comment]
Nevermind, I just needed some more time to wrap my head around bundles and dynamic imports.
