### ISSUE TITLE
de/d' in French

### ISSUE THREAD

**Issue by toschlog** [messageformat/messageformat#306]
Could this library be modified to provide a way to select correct prepositions?  

For example: In my app in English I use the phrase "Matt's party" where "Matt" is the current user's name.  For French this is "fête de Matt".  However, if my name were Andrew, it would be "fête d'Andrew".  The MessageFormat syntax seems well-suited to handle this.  It would look like this:

`{NAME, vowel,
  vowel {d'#}
  other {de #}
}`

(Ok, it's a little goofy to use "#" as the placeholder for the variable, but I'd keep it for consistency with "plural".)

I realize that this isn't in the ICU MessageFormat, but it seems a natural fit.  Would this be a good addition?  I'd be happy to write the code.

Thanks.

**Comment by eemeli** [comment]
This seems like a really good use case for a [custom formatter](http://messageformat.github.io/messageformat/guide/#custom-formatters). With one, something like this is possible:

```js
const firstFrenchVowel = (str) => ['a', 'e', 'i', 'o', 'u', 'y'].includes(str[0].toLowerCase())

function poss(val, lc) {
  if (lc === 'en') return `${val}'s`
  if (lc === 'fr') return firstFrenchVowel(val) ? `d'${val}` : `de ${val}`
  return val
}

const mf = new MessageFormat('fr', { customFormatters: { poss } })
const msg = mf.compile('La valise {foo, poss}')

msg({ foo: 'Andrew' }) // "La valise d'Andrew"
msg({ foo: 'George' }) // 'La valise de George'
```

Would that work for you?

**Comment by toschlog** [comment]
Yep, that works like a charm.  I should have ready more about the capabilities of MessageFormat.  Very cool!

Thanks.
