### ISSUE TITLE
Is it possible to wrap with [] instead of {} - custom formater questions

### ISSUE THREAD

**Issue by blurymind** [messageformat/messageformat#318]
Greetings :) 

We are trying to implement a format message that has the same syntax as 
https://github.com/YarnSpinnerTool/YarnSpinner/commit/c6e375675a066b85e7a447dd093d1a10df39fd6b#diff-72d441c9c1c3a30e47e7b5d9718827ae249fad0e6727035216e7c754af94eebcR9

in bondage.js, which is an implementation of yarnSpinner in js
https://github.com/hylyh/bondage.js/pull/73/files

Is it possible using the customFormatter option to do this in messageformat?
example of what it needs to look like
`I haven't seen [select {$gender} m="him" f="her" nb="them"].`
instead of 
`I haven't seen {gender, select, male {him} female {her} other {them}}.`

**Comment by blurymind** [comment]
@Chrissdroid is currently trying to implement this btw

**Comment by blurymind** [comment]
I suppose for our case, bondagejs can handle the [ ] , but we still need to figure out how to get from this
`I haven't seen [select {$gender} m="him" f="her" nb="them"].`
to this
`I haven't seen {gender, select, male {him} female {her} other {them}}.`

there order is different (select and gender), `gender` should be `$gender` 
male should be m(+the other genders are shortened)
parameters should be passed like this `m="him" `and not like this `male {him}`

**Comment by eemeli** [comment]
It sounds like you're not really asking for a custom formatter, but a parser for your custom syntax. With `messageformat`, that starts with the [lexer](https://github.com/messageformat/messageformat/blob/master/packages/parser/src/lexer.ts), from where the AST is [parsed](https://github.com/messageformat/messageformat/blob/master/packages/parser/src/parser.ts).

If you have an existing parser for your format, it should be relatively easy to generate from its AST (or whatever representation it uses for its parse result) the corresponding MessageFormat source, which you could then use with this library. That all sounds like a lot, but if you can do it during the build of your app, it won't have any effect on the runtime.

**Comment by eemeli** [comment]
Closing as answered.
