### ISSUE TITLE
Adding possibility to add object in front of runtime formatters for output

### ISSUE THREAD

**Issue by floratmin** [messageformat/messageformat#321]
Hello,

I need the possibility to collect all imports under an object. Then I will import the object with the functions into the file containing the messageformat string function. If this is welcome, I could create a pull request.

I will create the exported runtime in my own project, which would e.g. look like:
```js
import { time } from "@messageformat/runtime/lib/formatters";
import { en } from "@messageformat/runtime/lib/cardinals";

const number_en__currency_GBP_unit_width_narrow_2ztn9e = (function() {
    var opt = {"style":"currency","currency":"GBP","currencyDisplay":"narrowSymbol","unitDisplay":"narrow"};
    var nf = new Intl.NumberFormat(["en"], opt);
    return function(value) { return nf.format(value); }
})();

export const t = {
    time,
    number_en__currency_GBP_unit_width_narrow_2ztn9e,
    en
}
```
then I would import this with
```js
import { t } from './translation-functions';
```

What I will need is something like the following output:
```js
(d) => "Hello "
       + d.WORLD + " "
       + t.time(d.T, "en") + " " 
       + t.number_en__currency_GBP_unit_width_narrow_2ztn9e(d.V, "en") + " "
       + _.plural(d.RES, 0, _.en, { "0": "No", one: "One", other: "Many" }) + "."
```

I already made a fork where I get this output, I can also write tests and update the documentation.

**Comment by eemeli** [comment]
I have two questions on the idea:
1. Why do you need this?
2. What would your proposed API change look like?

**Comment by eemeli** [comment]
I think I'm still not understanding the deeper _why_ of all this. What is the expected benefit of this change? Does it allow for some new type of usage? Does it reduce payload size in some circumstances?

Based on your code samples, is there a Babel plugin or something like it that you're trying to also build, and is it the interface for that which is driving this suggested change?

**Comment by eemeli** [comment]
Regarding the `callPrefix` option, do I understand right that setting it to anything other than its default empty-string value would produce non-working code _except_ if the code is being post-processed by some other tool?

**Comment by eemeli** [comment]
Okay, so something like `callPrefix` is pretty much a non-starter, because that would lead to broken output in almost all cases.

Given that you'll be transforming the output in any case and this is a purely build-time concern, might it be easiest for you to just parse the output of `compileModule()` into an AST and work with that? It's structurally pretty simple, and the API _not_ providing customisability means that it's relatively stable as well.

**Comment by floratmin** [comment]
I use now a local copy of `compiler.ts` because I could not extend the `Compiler` class. I run into problems with `jest` and the module type exports from `@messageformat/date-skeleton` and `@messageformat/number-skeleton`. Then the function `biDiMarkText` is not exported. So I had to copy these two packages and the function declaration for `biDiMarkText` locally, otherwise, it would not work. Maybe I will use a parser when I have to rewrite my functions. Is there any timeline for version 2?
