### ISSUE TITLE
Compile only a single translation

### ISSUE THREAD

**Issue by jantimon** [messageformat/messageformat#328]
I really like the idea of precompiling translation keys during build time 👍

The current API is really cool:

```js
const MessageFormat = require("@messageformat/core");
const compileModule = require("@messageformat/core/compile-module");

const messageFormat = new MessageFormat("en");

console.log(
  compileModule(messageFormat, {
    productCount:
      "{ count, plural,\n   =0 {{formattedCount} Products}\n  one {{formattedCount} Product}\nother {{formattedCount} Products} } ",
  })
);
```

it generates:

```js
import { en } from "@messageformat/runtime/lib/cardinals";
import { plural } from "@messageformat/runtime";
export default {
  productCount: (d) => plural(d.count, 0, en, { "0": d.formattedCount + " Products", one: d.formattedCount + " Product", other: d.formattedCount + " Products" }) + " "
}
```

Unfortunately we would prefer to compile only a single translation so we would like to get the following output:

```js
import { en } from "@messageformat/runtime/lib/cardinals";
import { plural } from "@messageformat/runtime";
export default (d) => plural(d.count, 0, en, { "0": d.formattedCount + " Products", one: d.formattedCount + " Product", other: d.formattedCount + " Products" }) + " "
```

Or even more complicated: 

```js
import { en } from "@messageformat/runtime/lib/cardinals";
import { de } from "@messageformat/runtime/lib/cardinals";
import { plural } from "@messageformat/runtime";
export default ([
  (d) => plural(d.count, 0, en, { "0": d.formattedCount + " Products", one: d.formattedCount + " Product", other: d.formattedCount + " Products" }) + " ",
  (d) => plural(d.count, 0, de, { "0": d.formattedCount + " Produkte", one: d.formattedCount + " Produkt", other: d.formattedCount + " Produkte" }) + " "
])
```

Would it be possible to provide 3 public functions e.g. with the following api?

```js
getCardinalImport('en') -> // import { en } from "@messageformat/runtime/lib/cardinals";
getRuntimeImport() -> // import { plural } from "@messageformat/runtime";
getMessageFormater(messageFormat, "{ count, plural,\n   =0 {{formattedCount} Products}\n  one {{formattedCount} Product}\nother {{formattedCount} Products} } ") // -> (d) => plural(d.count, 0, en, { "0": d.formattedCount + " Products", one: d.formattedCount + " Product", other: d.formattedCount + " Products" }) + " "
```

**Comment by jantimon** [comment]
After some further investigations I realised that your utils `"@messageformat/core/compile-module"` would already solve that issue so I created pr #329

Solution with that PR in place:

```js
const MessageFormat = require("@messageformat/core");
const compileModule = require("@messageformat/core/compile-module");
const {Compiler, stringifyRuntime, getAvailableLocals}  = require("@messageformat/core/compile-module");

const messageFormat = new MessageFormat(["en", "de"]);
const messageFormat = new MessageFormat(["en", "de"]);
const { plurals } = messageformat;
const compiler = new Compiler(messageformat.options);
const exports = [
  compiler.compile(
    "{ count, plural,\n   =0 {{formattedCount} Products}\n  one {{formattedCount} Product}\nother {{formattedCount} Products} }",
    plurals[0],
    getAvailableLocals(messageformat)
  ),
  compiler.compile(
    "{ count, plural,\n   =0 {{formattedCount} Produkt}\n  one {{formattedCount} Produkt}\nother {{formattedCount} Produkte} }",
    plurals[1],
    getAvailableLocals(messageformat)
  )
];
const runtimeImports = stringifyRuntime(compiler.runtime);
console.log(
  runtimeImports,
  exports
)
```

**Comment by eemeli** [comment]
Hmm, apparently the `compileModule` types and docs are a bit misleading, as this actually already works:

```js
const mf = new MessageFormat('en')
compileModule(mf, "{ count, plural, =0 {{formattedCount} Products} one {{formattedCount} Product} other {{formattedCount} Products} } ")
> 'import { en } from "@messageformat/runtime/lib/cardinals";\n' +
  'import { plural } from "@messageformat/runtime";\n' +
  'export default (d) => plural(d.count, 0, en, { "0": d.formattedCount + " Products", one: d.formattedCount + " Product", other: d.formattedCount + " Products" }) + " "'
```

As for the array output where the message at index 0 is English & at index 1 in German, how did you envision the API would look like for determining that? I would think that it'd be clearer at all stages if the input and output used the locale keys to identify the language.

In general, unless there's a very clear benefit, I would really prefer not to expand the API to expose what's currently implementation internals. But a PR fixing the types would be nice.

**Comment by jantimon** [comment]
The concept behind my approach is a little bit wild 😄

Let me try to explain the idea behind it:

We are using a translation helper called `__` to pick the current language and return the required final value so for example 

`__('Hello {username}!', 'Alex')` -> `'Bonjour Alex!'`

As you can imagine it is using @messageformat behind the scenes.

To get the matching translation we are using a babel loader to import the dictionary like so:

```js
__('Hello {username}!', 'Alex')
```

```js
import __i18n_HelloUsername from './translations?key=HelloUsername';
__(__i18n_HelloUsername, 'Alex')
```

You might wonder why we are using the webpack resource query `'./translations?key=HelloUsername'`. Instead we could just use `import dictionary from './translations` to receive the entire dictionary.

The reason is that our approach enables webpack to reference only the used translations for each chunk. In other words pageA will only use translations of pageA and pageB will only use translations of pageB. Further more webpack will move shared translations into the common chunks and will also work fine with lazy loaded pages.

I hope this sounds somehow reasonable 😄 but still there is the question - why arrays?

Okay so in our build we predefined which languages are used e.g.: `['en-US', 'de-CH']` and our custom webpack loader also exposes this information to the runtime code:

```js
import languages from './translations?languages';

const languageIndex = languages.indexOf(currentLanguage)

export const __ = (translations, replacements) => translations[languageIndex](replacements)
```

As you can see our `__()` is only applying the current language to our array. That way we get a smaller production bundle.

Our input is for example:

```
{
  "Hello {username}!": { 
    'en-US': "Hello {username}!", 
    'de-CH': "Hallo {username}!", 
     ...
  },
  ...
}
```

and 

```js
__('Hello {username}!', 'Alex')
```

But after webpack and the minification of terser are done we get:

```
__([
  ()=> (d) => plural(d.count, 0, en, {...,
  ()=> (d) => plural(d.count, 0, de, {...
   ], 'Alex')
```

Sorry for this way to long answer but to summarize our build time optimizations:

- we strip 'en-US'
- we strip the translation key
- we add only the translations used on each page to its chunks

**Comment by eemeli** [comment]
That's still missing the bit where during the build you get the info about index 0 having an English message and index 1 having a German message. As you'll need to perform that mapping at some point, perhaps a Babel AST transform of the `compileModule()` output would be the most solid way of doing what you want?

**Comment by jantimon** [comment]
This is handled by the same loader which I am using for the dictionary transformation:

```js
module.exports = function translationDictionaryLoader(source) {
  const { languages } = this.getOptions();
  if (this.resourceQuery === "?lang") {
    return `export default (${JSON.stringify(languages)})`;
  } 
  ...
```

That way I can get the languages from the loader option during runtime:

```js
import languages from './translations?languages';
```

**Comment by cdaringe** [comment]
The current behavior **breaks the contract** provided by structured KV pairs when compiling a module, at least from the CLI. I want the precise **opposite** of the OP. 

Consider translations with just _one key_:

```yaml
# en.yaml
greet: hello
```

```yaml
# es.yaml
greet: hola
```

`pnpx messageformat <dir>`

yields =>

```js
{
  en: () => 'hello',
  es: () => 'hola'
}

```

As shown above, `greet` is **missing**. By just adding another key,

```yaml
# en.yaml
greet: hello
other: abc
```

```yaml
# es.yaml
greet: hola
other: efg
```


The correct shape is omitted:


```js
{
  en: { greet: () => 'hello', other: () => 'abc' },
  es: { greet: () => 'hola', other: () => 'efg' },
}
```

This broke me today unexpectedly where I had one translation with a single key. To keep the same structure, I know artificially add an additional key.

Is it agreed that this is/is not a problem? If this lossy behavior is _desired_ I think it should be opt-in only.
