### ISSUE TITLE
messageformat 3.0 with ngx-translate

### ISSUE THREAD

**Issue by MrRuke** [messageformat/messageformat#330]
Before I used to messageformat 2.1.0 with ngx-translate and it's working without any problems.

I created customCompiler and use messageFormat.compile, however with new version I can't do it. 
Method compile doesn't work with translation object, I tried to use Compiler, however it's return me object as string.

Before, 2.1.0 version return me this response
```
AUTH: {
      NAME: function(d) { return "name"; },
      EMAIL: function(d) { return "email"; },
}
```

When I use Compiler is return me string like NAME: () => "name", and this response doesn't work with ngx-translate.
How can I return interpolation functions like response from 2.1.0?

**Comment by eemeli** [comment]
For that kind of use with `messageformat@3`, you'll need a simple wrapper to walk through your input object to generate the functions. Something like this should do the trick:

```js
function compileDeep(mf, it) {
  if (typeof it === "string") return mf.compile(it);
  const res = {};
  for (const [key, value] of Object.entries(it))
    res[key] = compileDeep(mf, value);
  return res;
}
```

There, `mf` is expected to be an instance of `MessageFormat` and `it` is the object you're transforming.

**Comment by MrRuke** [comment]
It's working for me, thanks!
