### ISSUE TITLE
Custom formatters -  split values

### ISSUE THREAD

**Issue by MrRuke** [messageformat/messageformat#331]
Hi @eemeli!
I faced with problem, when I was trying to create custom formatter similar like Plural.

My case is formatter "ifElse", I need to set results for true and for false.
I used type "options" and "raw", however it don't work.
Options can't work with arguments, only with content (however this type more suitable for me)
When I use Raw it's return me one element as one string.

Maybe we need to expand options type for working with arguments? 
Possibly add special split symbol for Raw type can fix this problem, because we don't have any tools for control split.

Could you help me with this moment, because I don't understand how can I fix it.

**Comment by eemeli** [comment]
Could you post an example of what you're trying, including the messageformat source of your message, the arguments your custom formatter is getting, and the arguments that you would like it to get?

**Comment by MrRuke** [comment]
For example my string for translate
`{condition, ifElse, true{True result} false{False result}`
I set value for condition and check that this value setted. If we don't have argument for condition, I show False result otherwise I show True result
```
export function formatter(condition: any, locale: any, override: any): any {
  if (!('true' in override) || !('false' in override)) {
    return;
  }
  if (condition) {
    return override.true;
  }
  return override.false;
}

export const ifelse: any = {
  formatter,
  arg: 'options',
  id: 'ifelse',
};
```

**Comment by MrRuke** [comment]
If I set type "Option", I have object with `true: {True result} false:{False result}`, if I use "Raw", I have array `[0: true: {True result} false:{False result}]`

**Comment by MrRuke** [comment]
And I need to Object with arguments, like `true: {True result {val} }, false: {False result {val}` or Array with arguments `[0: True result {val}, 1: False result {val}]`

**Comment by eemeli** [comment]
Why not use just a `select` here?

```js
const mf = new MessageFormat('en')
const msg = mf.compile('{condition, select, true{True result} other{False result}}')

msg({ condition: true }) // 'True result'
msg({ condition: false }) // 'False result'
```

The syntax that's available for custom formatters won't support what you're looking for; if you want to go down that route, you should use some different syntax for the option values.

**Comment by MrRuke** [comment]
Well, in my cases, condition can be any value, not only Boolean. I get this value and I can't convert it when I set values.

However, if we can create wrapper around "select" it will fix my problem.
Can I do it? Make a formatter which be convert inputs and then send this on Select formatter.
Maybe we have any other variations for it? I can work only with values which get formatter and it's a reason, why I need it.

**Comment by MrRuke** [comment]
I create two different formatters for check that property is true or not.

However, I think that type='raw' is not correct naming, because first time I think that it's really raw values, not array.
