### ISSUE TITLE
message objects not shown in second example on http://messageformat.github.io/messageformat/react/

### ISSUE THREAD

**Issue by Yardie83** [messageformat/messageformat#336]
On http://messageformat.github.io/messageformat/react/ the second example does not show the two message objects for English and Finnish, but are included in the https://github.com/messageformat/messageformat/blob/master/docs/react.md

**Comment by eemeli** [comment]
You're right. It looks like the `{{ ... }}` is getting caught as a formatting command by the site tooling.
