### ISSUE TITLE
Console.warn is shown for consumers tests

### ISSUE THREAD

**Issue by Johannesklint** [messageformat/messageformat#352]
When running `jest` test for `React` components that uses `useMessage` you get `console.warn` all over.
It would be nice to disable the warnings when consumers of the library are running their tests.

**Comment by eemeli** [comment]
Have you tried using the [`<MessageProvider onError>` prop](http://messageformat.github.io/messageformat/api/react.messageproviderprops.onerror/)? That should allow you to build tests that do not follow the default behaviour of calling `console.warn`.

The `useMessage` test suite includes [some examples](https://github.com/messageformat/messageformat/blob/master/packages/react/src/use-message.test.tsx#L140) of this.

**Comment by Johannesklint** [comment]
That did the trick, thanks a bunch!
