### ISSUE TITLE
Localisation function not found for locale

### ISSUE THREAD

**Issue by EinfachHans** [messageformat/messageformat#376]
We use `ngx-translate-messageformat-compiler` (**5.0.1**) with `messageformat` (**2.3.0**) in a mobile application made with Capacitor. We get a lot of errors like these in the last two weeks:

**Localisation function not found for locale "PT"** (other locales as well) - See Sentry Error: https://sentry.io/share/issue/0a8f2d18e1af4df5b2e16fabfc84b519/

I really don't know what can cause this, anyone here that might help me? 😊

**Comment by eemeli** [comment]
This is almost certainly an issue with how you're using `ngx-translate-messageformat-compiler`; would suggest asking there for help? This in particular might be relevant: https://github.com/lephyrus/ngx-translate-messageformat-compiler#locale-initialization

**Comment by EinfachHans** [comment]
It says `By default, messageformat initializes all locales.` - i don't indicate any locales, so all should be initialised? 🤔

**Comment by eemeli** [comment]
You should be asking these questions in that project.
