### ISSUE TITLE
messageformat v4

### ISSUE THREAD

**Issue by probablyup** [messageformat/messageformat#392]
I see that v4 has published releases in the GitHub releases panel but the `messageformat` package on NPM is still on 2.x. Would love to start using the new package if possible over `@messageformat/core`.

**Comment by eemeli** [comment]
The v4 prereleases are available on npm as `messageformat@next`. Do note that it's primarily working with [Unicode MessageFormat 2.0](https://github.com/unicode-org/message-format-wg) messages rather than ICU MessageFormat; you'll also need the `@messageformat/icu-messageformat-1` for the latter.
