### ISSUE TITLE
If plurals has incompatible with a locale keys, all translations in the app break

### ISSUE THREAD

**Issue by bigcreate** [messageformat/messageformat#393]
we are updating the `messageformat` to v3+ in our applications, but faced with an issue that the whole translation in the app is failed because some plural keys are necessary, and some are redundant in different languages. It's hard to check and fix all locales and all translation files for each locale, besides, it's hard to teach translators to write translations in certain formats and with certain plural keys.
Could you add any backdoor to make the compiler/parser not so strict?
Or could you suggest anything about how it might be solved on our side?

**Comment by eemeli** [comment]
Could you give an example of what you mean? Only the `other` key is required for plurals.

**Comment by bigcreate** [comment]
@eemeli , for example, if for German we have `many` key, it fails
and yes, I was wrong about the required keys, I've thought that, for example, for Polish `one`, `few`, `many`, `other` are required, but it works without `many`, for example
So only redundant keys  like `many` for German lead to the error

**Comment by eemeli** [comment]
Ok, that makes sense. Really you ought to be able to warn and filter out those before formatting, but adding a default-`true` option like `strictPluralKeys` could be done. A PR on this would be welcome.

**Comment by bigcreate** [comment]
Hi @eemeli, could we expect that the issue might be resolved on your side? Unfortunately, we are fully packed with our own tasks. And to be honest, these breaking changes weren't in our plans, and sooner or later they will break our apps (we are not using yet v3 in prod)

**Comment by eemeli** [comment]
To be honest as well, this has rather low priority for me atm, and I might or might not get to fixing it myself sometime in the next few months. If you'd like to discuss a support contract, please reach out to me directly at eemeli@gmail.com.

**Comment by eemeli** [comment]
Fixed in #397 and #400.
