### ISSUE TITLE
On Activating Content Security Policy, MessageFormat transpiler throws 'unsafe-eval'

### ISSUE THREAD

**Issue by sureshputtur** [messageformat/messageformat#411]
Even in the MessageFormat latest version [3.2.0]. I see the issue. Is there any alternative library exist to use with ngneat/transoloco . 
Checked format library but it requires lot of changes in the code .  Similar issue has been raised long ago.
https://github.com/ngneat/transloco/issues/364

![image](https://github.com/messageformat/messageformat/assets/4947756/dd495340-6f75-407d-9da6-4a4c9a32c574)

**Comment by SlexAxton** [comment]
The library is intended to compile the messages into code. You can see examples in whichever guide matches your infra. If non-built messages are loaded, though, then the library will fall back to evaling the compiled output at runtime.

**Comment by eemeli** [comment]
Closing, as this is working as intended from the messageformat PoV.
