### ISSUE TITLE
Tests are out of sync with spec

### ISSUE THREAD

**Issue by catamorphism** [messageformat/messageformat#413]
Some tests need to be updated to reflect spec changes made during October 2023. For example:

https://github.com/messageformat/messageformat/blob/e0087bff312d759b67a9129eac135d318a1f0ce7/packages/mf2-messageformat/src/__fixtures/test-messages.json#L235

The test `"no braces"` is expected to generate a syntax error in the current version of `test-messages.json`. However, patterns are no longer required to begin with a `{` (see [the `pattern` production](https://github.com/unicode-org/message-format-wg/blob/main/spec/message.abnf#L14)), so this should be a valid pattern.

**Comment by eemeli** [comment]
As the current MF2 syntax is rather transitory https://github.com/unicode-org/message-format-wg/pull/500#pullrequestreview-1693532994, I'd prefer holding off from applying the relevant changes here until we've settled on where we're going with it.

**Comment by eemeli** [comment]
This was resolved in #414.
