### ISSUE TITLE
[feature] Add option to pass default timezone

### ISSUE THREAD

**Issue by SkeLLLa** [messageformat/messageformat#419]
Message format has an option to pass default currency to the constructor like
```
import MessageFormat from '@messageformat/core';

const mf = new MessageFormat('en', {currency: 'EUR'});
```

Alongside for date and time formatting it might be necessary to set `timeZone` (or pass to Intl.DateTimeFormat). By default it uses "current" locale. However, sometimes (especially using lib in node.js or other backend) it might be very helpful. And it will be more convenient, rather than specifying a new custom formatter.

Example:
```
import MessageFormat from '@messageformat/core';

const mf = new MessageFormat('en', {timeZone: 'UTC'});
```

**Comment by eemeli** [comment]
Yeah, that sounds like it could be a useful feature. I'd be happy to review a PR for this.
