### ISSUE TITLE
Number already formatted

### ISSUE THREAD

**Issue by XavierDupessey** [messageformat/messageformat#428]
Hello,

Compiling the source file:
```json
{
    "TEXT": "{miles, plural, one{# mile} other{# miles}}"
}
```

With `compileModule` from `@messageformat/core` (v3.3.0) produces:
```javascript
import { number, plural } from "@messageformat/runtime";
import { en } from "@messageformat/runtime/lib/cardinals";
export default {
  TEXT: (d) => plural(d.miles, 0, en, { one: number("en-us", d.miles, 0) + " mile", other: number("en-us", d.miles, 0) + " miles" })
}
```

Then, from the app, if we pass a number already formatted _as a string_ (e.g. `1,234.98`) then I get the message `NaN miles`.
Does it mean that this library does not allow this usage?

Thank you,
Xavier

**Comment by eemeli** [comment]
That's correct. The input value for the `plural` needs to either be a number, or a string that can be parsed with `Number()`. You probably need to pass two arguments to the message, so that one (an unformatted number) is used for the plural selection, and the second (the number formatted as a string) is used instead of the `#`.

**Comment by XavierDupessey** [comment]
Hey, thanks for your reply and sharing this practice.
I see that you are working on a v4, currently in Beta. Will this behavior change or will it be the same?

**Comment by eemeli** [comment]
`messageformat@4` is based on Unicode MessageFormat 2 (MF2), while thus far this library has been based on ICU MessageFormat (MF1).

It won't support parsing formatted numbers either, but it'll make it much easier to have the formatting be defined within the MF2 message syntax.

**Comment by XavierDupessey** [comment]
Got it! I hope we'll still have the option to specify the format directly within the app. I might be mistaken, but I believe the number of decimal digits we want to display typically doesn’t depend on the locale.

I'm closing this ticket now. Thanks again for your input!
