### ISSUE TITLE
[@messageformat/parser]: Parses escaped example wrong

### ISSUE THREAD

**Issue by floratmin** [messageformat/messageformat#436]
When I parse `parse("'{' {S, plural, other{# is a '#'}} '}'")` i get the wrong value:

```js
const parsedMessage = [
  {
    type: 'content',
    value: "{' {S, plural, other{# is a #}} }'",
    ctx: {
      offset: 0,
      line: 1,
      col: 1,
      text: "'{' {S, plural, other{# is a '#'}} '}'",
      lineBreaks: 0
    }
  }
]
```

**Comment by eemeli** [comment]
Thank you for reporting this! The lexer's rule for quoted escapes was indeed wrong, as the `[^]*?` regexp wasn't acting as non-greedily as it should, and I hadn't validated that the docs example actually worked.
